# configs/eb-alf.yaml
model_name: gpt-4o-mini
model_type: remote
down_sample_ratio: 1
language_only: False
eval_sets: []
chat_history: False
n_shots: 10
detection_box: False
multistep: False
resolution: 500
exp_name: baseline
env_feedback: True
tp: 1

# WorldMind specific settings
enable_worldmind: False

use_vision_discriminator: false
use_experience_trajectory: true
detailed_output: true
use_separate_summarization: false

eval_sets: ['base', 'common_sense', 'complex_instruction', 'spatial', 'visual_appearance']

# Goal Experience Settings
enable_goal_experience: true
goal_experience_top_k: 2

# Process Experience Settings
enable_process_experience: true
process_experience_top_k: 2

# Experience Refine Settings
enable_experience_refine: true

use_worldmind_template: true

resume: true
