name: worldmind
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - attrs=24.2.0=pyh71513ae_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.3=hb9d3cd8_1
  - ca-certificates=2024.11.26=h06a4308_0
  - certifi=2024.8.30=py39h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.3.0=py39h74842e3_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.27=h9033bb2_6
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.4=h5888daf_0
  - ffmpeg=4.3.2=hca11adc_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.0=py39h9399b63_0
  - freetype=2.12.1=h4a9f257_0
  - git-lfs=3.6.0=h647637d_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.2=h59595ed_0
  - imageio=2.36.1=pyh12aca89_1
  - imageio-ffmpeg=0.5.1=pyhd8ed1ab_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=2.2.1=h9c3ff4c_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libblas=3.9.0=25_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=25_linux64_openblas
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.9.1=h251f7ec_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=25_linux64_openblas
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libntlm=1.4=h7f98852_1002
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.0=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.3.0=hf544144_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.13.5=hfdd30dd_0
  - lz4-c=1.9.4=hcb278e6_0
  - matplotlib=3.9.1=py39hf3d152e_1
  - matplotlib-base=3.9.1=py39h0565ad7_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - olefile=0.47=pyhd8ed1ab_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openldap=2.6.5=h389dcaa_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhff2d567_1
  - pcre2=10.42=hebb0a14_1
  - pip=24.2=py39h06a4308_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pyqt=5.15.4=py39h5a03fae_0
  - pyqt5-sip=12.9.0=py39h5a03fae_0
  - python=3.9.20=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_0
  - python_abi=3.9=2_cp39
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.2=hb6262e9_11
  - quaternion=2023.0.4=py39hf15bc26_0
  - readline=8.2=h5eee18b_0
  - scipy=1.13.1=py39haf93ffa_0
  - sip=6.5.1=py39he80948d_2
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tmux=3.3a=h5eee18b_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.4.2=py39h8cd3c5a_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - unicodedata2=15.1.0=py39h8cd3c5a_1
  - wheel=0.44.0=py39h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxinerama=1.1.5=h27087fc_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.4.6=h5eee18b_1
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==1.1.1
      - addict==2.4.0
      - ai2thor==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.9
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anthropic==0.43.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - av==14.0.0
      - aws-requests-auth==0.4.3
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - blinker==1.9.0
      - botocore==1.35.71
      - cachetools==5.5.0
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - comm==0.2.2
      - datasets==3.1.0
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastapi==0.115.6
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - fire==0.7.0
      - flask==1.1.2
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.24.0
      - google-api-python-client==2.157.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - googleapis-common-protos==1.66.0
      - grpcio==1.69.0
      - grpcio-status==1.69.0
      - gym==0.23.0
      - gym-notices==0.0.8
      - h11==0.14.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.27.0
      - huggingface-hub==0.26.3
      - hydra-core==1.3.2
      - idna==3.10
      - importlib-metadata==8.5.0
      - interegular==0.3.3
      - ipykernel==6.29.5
      - ipython==8.18.1
      - isoduration==20.11.0
      - itsdangerous==1.1.0
      - jedi==0.19.2
      - jinja2==2.11.3
      - jiter==0.8.0
      - jmespath==1.0.1
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - lark==1.2.2
      - llvmlite==0.39.1
      - lmdeploy==0.6.3
      - markdown-it-py==3.0.0
      - markupsafe==1.1.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.1
      - mmengine-lite==0.10.5
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook-shim==0.2.4
      - numba==0.56.4
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai==1.60.0
      - opencv-python==4.10.0.84
      - outlines==0.0.46
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - peft==0.11.1
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - progressbar2==4.5.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - proto-plus==1.25.0
      - protobuf==5.29.0
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
    
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pygments==2.18.0
      - pynvml==12.0.0
      - python-json-logger==3.2.1
      - python-utils==3.9.1
      - python-xlib==0.33
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - qwen-vl-utils==0.0.8
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - revtok==0.0.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.4.5
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - setuptools==68.2.2
      - shortuuid==1.0.13
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.41.3
      - sympy==1.13.3
      - termcolor==2.5.0
      - terminado==0.18.1
      - tiktoken==0.8.0
      - tinycss2==1.4.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==2.4.0
      - torchvision==0.19.0
      - traitlets==5.14.3
      - transformers==4.46.2
      - triton==3.0.0
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2024.2
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - urllib3==1.26.20
      - uvicorn==0.32.1
      - vocab==0.0.5
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==1.0.1
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.18.3
