name: embench_nav
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.11.26=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.21=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.3.0
      - addict==2.4.0
      - ai2thor==5.0.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anthropic==0.43.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - aws-requests-auth==0.4.3
      - blinker==1.9.0
      - botocore==1.35.90
      - cachetools==5.5.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.2.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - fastapi==0.115.8
      - filelock==3.17.0
      - fire==0.7.0
      - flask==3.1.0
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.24.0
      - google-api-python-client==2.159.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - googleapis-common-protos==1.66.0
      - grpcio==1.69.0
      - grpcio-status==1.69.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - h11==0.14.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.28.1
      - hydra-core==1.3.2
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.5.2
      - interegular==0.3.3
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - jiter==0.8.2
      - jmespath==1.0.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - lark==1.2.2
      - llvmlite==0.43.0
      - lmdeploy==0.7.0.post2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mmengine-lite==0.10.6
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==1.58.1
      - opencv-python==4.10.0.84
      - outlines==0.0.46
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.11.1
      - pillow==10.4.0
      - platformdirs==4.3.6
      - progressbar2==4.5.0
      - propcache==0.2.1
      - proto-plus==1.25.0
      - protobuf==5.29.3
      - psutil==6.1.1
 
      - pyarrow==19.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycountry==24.6.1
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pynvml==12.0.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-utils==3.9.1
      - python-xlib==0.33
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.5.2
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.45.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==2.5.0
      - tiktoken==0.8.0
      - together==1.3.13
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.48.3
      - triton==3.1.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uritemplate==4.1.1
      - urllib3==1.26.20
      - uvicorn==0.34.0
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.18.3
      - zipp==3.21.0
