name: embench_man2
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.2.0=pyh71513ae_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.3=heb4867d_0
  - ca-certificates=2024.12.14=hbcca054_0
  - certifi=2024.12.14=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cuda-version=12.6=h7480c83_3
  - curl=8.8.0=he654da7_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.11=py39hf88036b_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h5888daf_0
  - ffmpeg=3.2.4=1
  - freetype=2.12.1=h267a509_2
  - git-lfs=3.5.1=h647637d_1
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9e=h0b41bf4_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libcurl=8.8.0=hca28451_1
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=25_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.43=h2797004_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.3.0=h0fcbabc_4
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.49.2=hb9d3cd8_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvmlite=0.42.0=py39h174d805_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - nccl=2.23.4.1=h2b5d15b_3
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numba=0.59.1=py39h615d6bd_0
  - numpy=1.26.4=py39h474f0d3_0
  - olefile=0.47=pyhd8ed1ab_0
  - openjpeg=2.5.0=h7d73246_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.18.0=pyhd8ed1ab_1
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - python=3.9.19=h0755675_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.9=5_cp39
  - pyzmq=26.2.0=py39h4e4fb57_3
  - quaternion=2023.0.4=py39hf15bc26_0
  - readline=8.2=h8228510_1
  - rhash=1.4.3=hd590300_2
  - setuptools=75.6.0=pyhff2d567_1
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py39h8cd3c5a_1
  - tqdm=4.67.0=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_1
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.2.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anthropic==0.45.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.7.0
      - async-timeout==5.0.1
      - av==14.0.1
      - beautifulsoup4==4.12.3
      - blinker==1.9.0
      - cachetools==5.5.1
      - cffi==1.14.2
      - charset-normalizer==3.4.0
      - click==8.1.8
      - cloudpickle==3.1.0
      - configargparse==1.7
      - contourpy==1.3.0
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - datasets==3.2.0
      - defusedxml==0.7.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - einops==0.8.0
      - farama-notifications==0.0.4
      - fastapi==0.115.6
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - fire==0.7.0
      - flask==3.0.3
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gdown==5.2.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.24.0
      - google-api-python-client==2.159.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.4
      - googleapis-common-protos==1.66.0
      - grpcio==1.70.0
      - grpcio-status==1.70.0
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.27.0
      - hydra-core==1.3.2
      - idna==3.10
      - importlib-resources==6.5.2
      - interegular==0.3.3
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-widgets==3.0.13
      - lark==1.2.2
      - lmdeploy==0.6.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mmengine-lite==0.10.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - natsort==8.4.0
      - nbformat==5.10.4
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - open3d==0.18.0
      - openai==1.58.1
      - outlines==0.0.46
      - pandas==2.2.3
      - peft==0.11.1
      - pillow==11.0.0
      - plotly==5.24.1
      - propcache==0.2.1
      - proto-plus==1.25.0
      - protobuf==5.29.2
      - py-cpuinfo==9.0.0
  
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pynvml==12.0.0
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.8
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - retrying==1.3.4
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-learn==1.6.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - segment-anything==1.0
      - sentencepiece==0.2.0
      - shortuuid==1.0.13
      - sniffio==1.3.1
      - soupsieve==2.6
      - stable-baselines3==2.4.0
      - starlette==0.41.3
      - supervision==0.25.1
      - sympy==1.13.1
      - tenacity==9.0.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.4.0
      - torchvision==0.19.0
      - transform3d==0.0.4
      - transformers==4.47.1
      - transforms3d==0.4.2
      - triton==3.0.0
      - tzdata==2024.2
      - ultralytics==8.3.61
      - ultralytics-thop==2.0.13
      - uritemplate==4.1.1
      - urllib3==2.2.3
      - uvicorn==0.34.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.18.3